### ISSUE TITLE
Is there any way to hide non-critical logs to stdout?

### ISSUE THREAD

**Issue by u3Izx9ql7vW4** [automl/DEHB#85]
Hi, 

The dehb package is producing a large amount of logs into stdout, and they're not contained within the dehb namespace, but rather polluting the global namespace, which makes it difficult to read logs coming from any host program. 

Is there anyway to turn off this behavior and only have it log errors like other programs?

Thanks,

**Comment by Bronzila** [comment]
Hey, I'm assuming you are using `dehb.run`. If so, have you tried using the verbosity flag, i.e. `dehb.run(..., verbose=False)`. Then you should only be left with outputs regarding state saving/logging.

**Comment by Bronzila** [comment]
Anyways, thanks for you issue! Since the state saving logs could also fill stdout with a lot of logs, we should maybe think about adding a verbosity level for the whole DEHB class and not just the `run` function.

**Comment by Bronzila** [comment]
Nice to hear, that this could solve your issue. In the upcoming release the logging structure will anyways be adjusted since currently for every instantiation of DEHB the logs will be written to some specific file. In the upcoming release it will just be written to `dehb.log` and thus will be overwritten by new instatiations of DEHB (assuming that you do not adjust the output path).

**Comment by Neeratyoy** [comment]
> Will this affect the ability to run multiple DEHB instances running simultaneously?

This should not, assuming each DEHB instance is an independent optimization run since then the `output_path` should vary.
@Bronzila could you please correct me or add anything if required.

**Comment by Bronzila** [comment]
Sorry, I must have overlooked your comment @u3Izx9ql7vW4 
As @Neeratyoy pointed out, as long as each DEHB instance has a unique `output_path` no results will be overwritten.
