### ISSUE TITLE
Test backward compatibility with NumPy2.0

### ISSUE THREAD

**Issue by Neeratyoy** [automl/DEHB#91]
For now we should limit Numpy dependency to be [`<2.0`](https://numpy.org/doc/stable/release/2.0.0-notes.html#highlights).
Given we manipulate arrays and they form the crucial data structures for the algorithm, we should explicitly test what breaks and how significant changes are required for the new Numpy version.

**Comment by eddiebergman** [comment]
I highly doubt dehb would break, it more seems for libraries building on top of numpy, doing C ABI stuffs.

Of course worth checking, but it would take 5 minutes to test

**Comment by Bronzila** [comment]
Yup, I checked it yesterday and it seems like ConfigSpace breaks with Numpy 2.0 - That's also the reason why our tests crash at the moment.

**Comment by eddiebergman** [comment]
Yup, well aware. You can try this version of ConfigSpace which hopefully gets released soon: https://github.com/automl/ConfigSpace/pull/346

**Comment by Bronzila** [comment]
Just checked out, whether DEHB itself is affected by numpy 2.0 changes by using ConfigSpaces PR version and DEHB does not crash. I still added the limitation to numpy <2.0 to `pyproject.toml` while we are waiting for the new ConfigSpace version. I will also create an issue for this in order to not forget about it.
